TRANSPORT_PACKET_SENT = 'transport:packet_sent'
TRANSPORT_PACKET_RECEIVED = 'transport:packet_received'
TRANSPORT_PARAMETERS_SET = 'transport:parameters_set'
TRANSPORT_PARAMETERS_RESTORED = 'transport:parameters_restored'
RECOVERY_METRICS_UPDATED = 'recovery:metrics_updated'
